# Generated by Django 3.2.4 on 2021-06-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gun2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='zip',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
